M48
; DRILL file KiCad 10.0.3 date 2026-07-12T13:30:32
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-12T13:30:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X94.0Y-27.6
X94.0Y-89.8
X223.8Y-89.8
X224.0Y-27.6
T2
X144.4Y-35.2
M30
