M48
; DRILL file KiCad 10.0.4 date 2026-06-23T08:16:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-23T08:16:20-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X104.0Y-48.0
X104.5Y-122.0
X201.0Y-48.0
X201.5Y-122.0
T2
X192.0Y-77.4
M30
